import turtle

# 设置画布大小
turtle.setup(800, 600)

# 画笔设置
turtle.pensize(2)
turtle.speed(10)

# 绘制电脑屏幕
turtle.penup()
turtle.goto(-300, 200)
turtle.pendown()
turtle.fillcolor('#8FAADC')
turtle.begin_fill()
turtle.goto(300, 200)
turtle.goto(300, -200)
turtle.goto(-300, -200)
turtle.goto(-300, 200)
turtle.end_fill()

# 绘制电脑边框
turtle.penup()
turtle.goto(-320, 220)
turtle.pendown()
turtle.fillcolor('grey')
turtle.begin_fill()
turtle.goto(320, 220)
turtle.goto(320, -220)
turtle.goto(-320, -220)
turtle.goto(-320, 220)
turtle.end_fill()

# 绘制桌面
turtle.penup()
turtle.goto(-400, -250)
turtle.pendown()
turtle.fillcolor('#CA9C70')
turtle.begin_fill()
turtle.goto(400, -250)
turtle.goto(400, -300)
turtle.goto(-400, -300)
turtle.goto(-400, -250)
turtle.end_fill()

# 绘制少女
turtle.penup()
turtle.goto(0, 0)
turtle.pendown()
turtle.fillcolor('pink')
turtle.begin_fill()
turtle.circle(50)
turtle.end_fill()

# 绘制少女的头发
turtle.penup()
turtle.goto(0, 50)
turtle.pendown()
turtle.fillcolor('brown')
turtle.begin_fill()
turtle.circle(60, 120)
turtle.goto(0, 50)
turtle.end_fill()
turtle.penup()
turtle.goto(0, 50)
turtle.pendown()
turtle.right(180)
turtle.fillcolor('brown')
turtle.begin_fill()
turtle.circle(-60, 120)
turtle.goto(0, 50)
turtle.end_fill()

# 绘制少女的眼睛
turtle.penup()
turtle.goto(-20, 70)
turtle.pendown()
turtle.fillcolor('white')
turtle.begin_fill()
turtle.circle(10)
turtle.end_fill()
turtle.penup()
turtle.goto(-20, 80)
turtle.pendown()
turtle.fillcolor('black')
turtle.begin_fill()
turtle.circle(3)
turtle.end_fill()

turtle.penup()
turtle.goto(20, 70)
turtle.pendown()
turtle.fillcolor('white')
turtle.begin_fill()
turtle.circle(10)
turtle.end_fill()
turtle.penup()
turtle.goto(20, 80)
turtle.pendown()
turtle.fillcolor('black')
turtle.begin_fill()
turtle.circle(3)
turtle.end_fill()

# 绘制少女的嘴巴
turtle.penup()
turtle.goto(0, 50)
turtle.pendown()
turtle.right(90)
turtle.circle(-30, 180)
turtle.penup()
turtle.goto(0, 50)
turtle.pendown()
turtle.left(90)

# 绘制少女的身体
turtle.penup()
turtle.goto(0, -20)
turtle.pendown()
turtle.fillcolor('pink')
turtle.begin_fill()
turtle.circle(80)
turtle.end_fill()

# 显示画布
turtle.done()