import turtle

# 绘制少女头发
turtle.penup()
turtle.goto(-60, 90)
turtle.pendown()
turtle.fillcolor('#8E5829')  # 设置头发颜色
turtle.begin_fill()
turtle.right(90)
turtle.circle(60, 180)
turtle.right(90)
turtle.forward(120)
turtle.end_fill()

# 绘制少女脸部
turtle.penup()
turtle.goto(0, 100)
turtle.pendown()
turtle.fillcolor('#FDD7E4')  # 设置脸部颜色
turtle.begin_fill()
turtle.circle(40)
turtle.end_fill()

# 绘制少女眼睛
turtle.penup()
turtle.goto(-20, 120)
turtle.pendown()
turtle.fillcolor('white')
turtle.begin_fill()
turtle.circle(10)
turtle.end_fill()
turtle.penup()
turtle.goto(20, 120)
turtle.pendown()
turtle.fillcolor('white')
turtle.begin_fill()
turtle.circle(10)
turtle.end_fill()
turtle.penup()
turtle.goto(-15, 125)
turtle.pendown()
turtle.fillcolor('black')
turtle.begin_fill()
turtle.circle(5)
turtle.end_fill()
turtle.penup()
turtle.goto(15, 125)
turtle.pendown()
turtle.fillcolor('black')
turtle.begin_fill()
turtle.circle(5)
turtle.end_fill()

# 绘制少女嘴巴
turtle.penup()
turtle.goto(0, 80)
turtle.pendown()
turtle.right(90)
turtle.circle(20, 180)

# 绘制少女身体
turtle.penup()
turtle.goto(0, 50)
turtle.pendown()
turtle.fillcolor('#FDD7E4')  # 设置身体颜色
turtle.begin_fill()
turtle.right(90)
turtle.forward(60)
turtle.right(90)
turtle.forward(40)
turtle.right(90)
turtle.forward(60)
turtle.end_fill()

# 绘制少女裙子
turtle.penup()
turtle.goto(0, 10)
turtle.pendown()
turtle.fillcolor('#FFB6C1')  # 设置裙子颜色
turtle.begin_fill()
turtle.right(90)
turtle.forward(40)
turtle.right(90)
turtle.forward(60)
turtle.right(90)
turtle.forward(40)
turtle.right(90)
turtle.forward(60)
turtle.end_fill()

# 绘制少女腿
turtle.penup()
turtle.goto(-20, -10)
turtle.pendown()
turtle.fillcolor('#FDD7E4')  # 设置腿的颜色
turtle.begin_fill()
turtle.right(120)
turtle.forward(50)
turtle.right(60)
turtle.forward(20)
turtle.right(120)
turtle.forward(50)
turtle.end_fill()
turtle.penup()
turtle.goto(20, -10)
turtle.pendown()
turtle.fillcolor('#FDD7E4')  # 设置腿的颜色
turtle.begin_fill()
turtle.right(60)
turtle.forward(50)
turtle.right(120)
turtle.forward(20)
turtle.right(60)
turtle.forward(50)
turtle.end_fill()

# 绘制少女鞋子
turtle.penup()
turtle.goto(-25, -35)
turtle.pendown()
turtle.fillcolor('black')
turtle.begin_fill()
turtle.right(90)
turtle.forward(20)
turtle.right(90)
turtle.forward(20)
#画鞋底
turtle.right(90)
turtle.forward(10)
turtle.right(90)
turtle.forward(20)
turtle.right(90)
turtle.forward(10)
turtle.end_fill()
turtle.penup()
turtle.goto(25, -35)
turtle.pendown()
turtle.fillcolor('black')
turtle.begin_fill()
turtle.right(90)
turtle.forward(10)
turtle.right(90)
turtle.forward(20)
turtle.right(90)
turtle.forward(10)
turtle.end_fill()

turtle.hideturtle()

turtle.done()